Adds NeoCSV as a dependency and provides  asCSV and asJSON for ...
pharo-rdbms/Pharo-MySQL pull request #16
Opened 2021-07-13 11:27 UTC by tblanchard

MySQLRow.  Also nicer column indexing allowing int or name.

Basically a few methods I added after finding it nearly impossible to generate a report using the result processing methods available.

2021-07-13 11:34 UTC, tblanchard commented
I should add some tests before we merge this.  Also, tests are failing due to permissions. 

@gcotelli can you let me know how we fix this?  Also would like a second  set of eyes on this change.

2021-07-13 11:35 UTC, gcotelli commented
I will take a look at the permissions issue.

2021-07-13 11:47 UTC, gcotelli commented
@tblanchard the build is running again. Take look because the baseline is referencing a non-existent NeoCSV group or package .

2021-07-13 12:00 UTC, tblanchard commented
@gcotelli Thanks, I've pushed a fix for that - mistyped package name.

2021-07-13 12:15 UTC, gcotelli commented
Looks like we hit a smalltalkCI bug because it is trying to write the coverage info into an invalid place:
```
Writing LCOV coverage info to: /home/runner/work/Pharo-MySQL/Pharo-MySQL/coverage/lcov.info
FileDoesNotExistException: '/home/runner/work/Pharo-MySQL/Pharo-MySQL/MySQL-Core/MySQLBindError.class.st'
```

Maybe it's because the project has the package folders in the root one. I always put my packages inside a source folder and never hitted this error.

2021-07-13 12:56 UTC, gcotelli commented
@tblanchard I think I've found the problem. Some of the files have an invalid case, for example `MySQLResultSet` was written somehow as `MysqlResultSet.class.st` and smalltalkCI needs to locate the file to calculate the hash to export the coverage data. I will try to locate the invalid files and rename them but give me some time.

2021-07-13 13:19 UTC, gcotelli commented
Ok, now that the build is working let me see the changes.

I think that the CSV conversion is better handled by adding the methods as extensions into another package and providing an optional group to load in the baseline. Because right now it adds a hard dependency to NeoCSV for everyone wanting to use the package, even if they don't want to use the CSV conversion stuff. What do you think?

2021-07-13 15:45 UTC, tblanchard commented
@gcotelli I kind of agree with you on the CSV, I was trying to find a nice place to put it but maybe the best place is my own application code.   I am putting together a BaselineOf for a project I am starting and just trying to get all the dependencies to load cleanly.  I think I will revert the CSV piece and add some tests before merging.  Thanks for your input and for quickly diagnosing the issue!

2021-07-13 15:47 UTC, tblanchard commented
Oh, actually, I see what you mean about making it an optional load from MySQL.  I will look at that.

2021-07-13 17:29 UTC, astares commented
@tblanchard / @gcotelli 

I would prefer to not load NeoCSV with the core group. The **core** should really only be the essential stuff and not anyone needs or uses 

Why not have an additional group "core-extended" in baseline with the dependency -  so one can pick either "core" group (for rare stuff) or the "core-extended" for core + additional support like CSV.

2021-07-13 20:37 UTC, astares commented
Only a minor thing: maybe you should call own groups "Core" instead "core", "Glorp" instead of "glorp", .... 
Then it is like in other BaselineOf classes.

Usually only meta-groups like "all" or "default" are lowercase.

2021-07-13 21:30 UTC, tblanchard commented
> Only a minor thing: maybe you should call own groups "Core" instead "core", "Glorp" instead of "glorp", ....
> Then it is like in other BaselineOf classes.
> 
> Usually only meta-groups like "all" or "default" are lowercase.

I moved it out to a group csv which requires core.  Do you think we will break any existing projects by renaming?

2021-07-13 21:41 UTC, gcotelli commented
I also use group names capitalized. 
But yes, if you remove the old group names this will break dependencies for sure. Maybe we can add the new groups capitalized and a capitalized version of the previous groups (so `core` will continue to work, but also `Core`). And give a notice on the release notes of this version and a time window for users to migrate. Once the time window has passed we can delete the lowercase groups in the next release.

2021-07-13 21:42 UTC, tblanchard commented
@gcotelli That sounds like the best idea.

2021-07-14 12:23 UTC, gcotelli requested changes
- Please update the group names as discussed
- The new functionality is missing some test cases

2021-07-14 12:23 UTC, gcotelli commented on BaselineOfMySQL/BaselineOfMySQL.class.st
>  		group: 'core' with: 'MySQL-Core'.
Add a new `Core` group

2021-07-14 12:23 UTC, gcotelli commented on BaselineOfMySQL/BaselineOfMySQL.class.st
> +		group: 'csv' with: 'MySQL-CSV'.
```suggestion
		group: 'CSV' with: 'MySQL-CSV'.
```

2021-07-14 21:13 UTC, gcotelli commented
@tblanchard apparently the problem is that you're trying to define a group Glorp and it collides with the Glorp baseline definition. Try a different name for the group? Sometimes Metacello is pretty awkward with the errors.

2021-07-14 21:37 UTC, tblanchard commented on BaselineOfMySQL/BaselineOfMySQL.class.st
>  		group: 'core' with: 'MySQL-Core'.
core is now Core

2021-07-14 21:43 UTC, tblanchard commented
I'm done screwing with this.  I have the methods I need to support the asCSV and I will add that in my application.  I did make the changes.

> Only a minor thing: maybe you should call own groups "Core" instead "core", "Glorp" instead of "glorp", ....
> Then it is like in other BaselineOf classes.
> 
> Usually only meta-groups like "all" or "default" are lowercase.

glorp is staying glorp because Glorp breaks the tests as it conflicts with package Glorp and I'm out of patience with this.  I have a project to kick off.  Happy to review someone else's efforts towards this.  I've also given up on putting in CSV at all.

2021-07-14 22:55 UTC, merged